version: '3.5'

networks:
  {{cookiecutter.app_name}}_test:
    external: false

services:

  pg-{{cookiecutter.app_name}}-testing:
    image: "postgres:14.2"
    container_name: pg-{{cookiecutter.app_name}}-testing
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=Finkargo
      - POSTGRES_PASSWORD=Finkargo
      - POSTGRES_DB={{cookiecutter.app_name}}
      - DEBUG=True
    restart: always
    networks:
      - {{cookiecutter.app_name}}_test

  redis-{{cookiecutter.app_name}}-testing:
    image: "redis:latest"
    container_name: redis-{{cookiecutter.app_name}}-testing
    ports:
      - 6378:6379
    networks:
      - {{cookiecutter.app_name}}_test